# Generated by Django 3.0 on 2019-12-14 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semester', '0001_initial'),
        ('student', '0002_stdcomplatedsemester_stdrunningsemester'),
        ('cource', '0009_auto_20191214_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cource.Cource')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semester.Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
