# Generated by Django 3.0 on 2019-12-14 14:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semester', '0001_initial'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('techer_id', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('pn_number', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('addres', models.CharField(blank=True, max_length=1000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('admited_semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='semester.Semester')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.Department')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.Program')),
            ],
        ),
    ]
