# Generated by Django 3.0 on 2019-12-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='techer_id',
            new_name='teacher_id',
        ),
    ]
