# Generated by Django 3.0 on 2019-12-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_remove_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
