# Generated by Django 3.0 on 2019-12-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
