# Generated by Django 3.0 on 2019-12-14 15:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='lab',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('S', 'Sunday'), ('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('R', 'Thursday')], default='S', max_length=30)),
                ('start', models.TimeField(default=datetime.time)),
                ('duration', models.CharField(choices=[('1.20', '1.20'), ('2', '2'), ('3', '3')], default='1.20', max_length=10)),
                ('end', models.TimeField(default=datetime.time)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cource.Section')),
            ],
        ),
    ]
