# Generated by Django 3.0 on 2019-12-14 15:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('cource', '0002_auto_20191214_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='bulding',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.Bulding'),
        ),
        migrations.AddField(
            model_name='classes',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='room_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cource',
            name='credit',
            field=models.IntegerField(choices=[(
                '1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('4.5', '4.5')], default='3'),
        ),
        migrations.CreateModel(
            name='CourceLab',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('S', 'Sunday'), ('M', 'Monday'), ('T', 'Tuesday'), (
                    'W', 'Wednesday'), ('R', 'Thursday')], default='S', max_length=30)),
                ('start', models.TimeField(default=datetime.time)),
                ('duration', models.CharField(choices=[
                 ('1.20', '1.20'), ('2', '2'), ('3', '3')], default='1.20', max_length=10)),
                ('end', models.TimeField(default=datetime.time)),
                ('room_number', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('bulding', models.ForeignKey(
                    default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.Bulding')),
                ('section', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='cource.Section')),
            ],
        ),
    ]
