# Generated by Django 3.0 on 2019-12-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cource', '0006_auto_20191214_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='room_number',
            field=models.IntegerField(),
        ),
    ]
