# Generated by Django 3.0 on 2019-12-14 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0001_initial'),
        ('cource', '0009_auto_20191214_2143'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StdRunningSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('Semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semester.Semester')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cource.Section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StdComplatedSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('Semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semester.Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
